export const PERFUME_BRANDS = [
  { name: "Chanel", domain: "chanel.com" },
  { name: "Dior", domain: "dior.com" },
  { name: "Giorgio Armani", domain: "armani.com" },
  { name: "Yves Saint Laurent", domain: "ysl.com" },
  { name: "Tom Ford", domain: "tomford.com" },
  { name: "Gucci", domain: "gucci.com" },
  { name: "Prada", domain: "prada.com" },
  { name: "Versace", domain: "versace.com" },
  { name: "Dolce & Gabbana", domain: "dolcegabbana.com" },
  { name: "Burberry", domain: "burberry.com" },
  { name: "Givenchy", domain: "givenchy.com" },
  { name: "Hermès", domain: "hermes.com" },
  { name: "Maison Francis Kurkdjian", domain: "franciskurkdjian.com" },
  { name: "Creed", domain: "creedboutique.com" },
  { name: "Jo Malone", domain: "jomalone.com" },
  { name: "Narciso Rodriguez", domain: "narcisorodriguezparfums.com" },
  { name: "Carolina Herrera", domain: "carolinaherrera.com" },
  { name: "Jean Paul Gaultier", domain: "jeanpaulgaultier.com" },
  { name: "Rabanne", domain: "rabanne.com" },
  { name: "Montale", domain: "montaleparfums.com" },
  { name: "Mancera", domain: "manceraparfums.com" },
  { name: "Byredo", domain: "byredo.com" },
  { name: "Le Labo", domain: "lelabofragrances.com" },
  { name: "Diptyque", domain: "diptyqueparis.com" },
  { name: "Xerjoff", domain: "xerjoff.com" },
] as const

export const PERFUME_BRAND_NAMES = PERFUME_BRANDS.map((brand) => brand.name)
